[package]
name = "file-path-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "4.1.0"
walkdir = "2.3.3"
regex = "1.4.5"
